# Generated by Django 2.1.2 on 2018-11-11 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5, verbose_name='Type')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('call_id', models.CharField(max_length=32, verbose_name='Call ID')),
                ('source', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)], verbose_name='Source number')),
                ('destination', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)], verbose_name='Destination number')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration time')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Phone Call',
                'verbose_name_plural': 'Phone Calls',
                'ordering': ['-call_id', 'timestamp'],
            },
        ),
    ]
